# Generated by Django 3.1.5 on 2022-06-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdata',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
